version: "3.9"

name: ignite3

x-ignite-def:
  &ignite-def
  image: apacheignite/ignite:3.1.0
  volumes:
    - ./node-config.json:/opt/ignite/etc/ignite-config.conf

services:
  node1:
    << : *ignite-def
    command: --node-name node1
    ports:
      - 10300:10300
      - 10800:10800
    environment:
      - ADVERTISED_CLIENT_ADDR=localhost:10800
  node2:
    << : *ignite-def
    command: --node-name node2
    ports:
      - 10301:10300
      - 10801:10800
    environment:
      - ADVERTISED_CLIENT_ADDR=localhost:10801
  node3:
    << : *ignite-def
    command: --node-name node3
    ports:
      - 10302:10300
      - 10802:10800
    environment:
      - ADVERTISED_CLIENT_ADDR=localhost:10802

# Init cluster:
# docker run --rm -it --network=host -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 apacheignite/ignite:3.0.0 cli
# cluster init --name=mycluster --metastorage-group=node1
# CREATE TABLE Person (id INT PRIMARY KEY, name VARCHAR);
# INSERT INTO Person (id, name) VALUES (-1, 'Foo Bar');
